'use server'

import { revalidatePath } from 'next/cache'
import { createServiceRoleClient } from '@/lib/supabase/server'
import { createDevisSchema } from '@/lib/validations/dossier'
import { logAudit } from '@/lib/audit'
import { getSession } from '@/lib/auth'
import type { ActionResult } from '@/lib/types'

export async function createDevisAction(formData: FormData): Promise<ActionResult> {
  const session = await getSession()
  const raw: Record<string, unknown> = {}
  for (const [key, value] of formData.entries()) { raw[key] = value }

  const parsed = createDevisSchema.safeParse(raw)
  if (!parsed.success) return { success: false, errors: parsed.error.flatten().fieldErrors }

  const supabase = await createServiceRoleClient()

  const { data, error } = await supabase
    .from('devis')
    .insert({
      organization_id: session.organization.id,
      numero: '', // Auto-generated by trigger
      client_id: parsed.data.client_id,
      contact_id: parsed.data.contact_id || null,
      formation_id: parsed.data.formation_id || null,
      objet: parsed.data.objet,
      date_validite: parsed.data.date_validite,
      remise_pourcent: parsed.data.remise_pourcent,
      conditions_particulieres: parsed.data.conditions_particulieres || null,
      notes_internes: parsed.data.notes_internes || null,
      created_by: session.user.id,
    })
    .select()
    .single()

  if (error) {
    console.error('[Create Devis]', error)
    return { success: false, error: 'Erreur lors de la création du devis' }
  }

  await logAudit({ action: 'create', entity_type: 'devis', entity_id: data.id })
  revalidatePath('/dashboard/devis')
  return { success: true, data }
}

export async function addDevisLigneAction(devisId: string, formData: FormData): Promise<ActionResult> {
  const session = await getSession()
  const supabase = await createServiceRoleClient()

  const designation = formData.get('designation') as string
  const quantite = parseFloat(formData.get('quantite') as string) || 1
  const prix_unitaire_ht = parseFloat(formData.get('prix_unitaire_ht') as string) || 0
  const unite = (formData.get('unite') as string) || 'forfait'
  const description = formData.get('description') as string

  if (!designation) return { success: false, error: 'Désignation requise' }

  const montant_ht = quantite * prix_unitaire_ht

  // Get current max position
  const { data: lignes } = await supabase
    .from('devis_lignes')
    .select('position')
    .eq('devis_id', devisId)
    .order('position', { ascending: false })
    .limit(1)

  const position = (lignes?.[0]?.position ?? -1) + 1

  const { error } = await supabase
    .from('devis_lignes')
    .insert({
      devis_id: devisId,
      designation,
      description: description || null,
      quantite,
      unite,
      prix_unitaire_ht,
      montant_ht,
      position,
    })

  if (error) return { success: false, error: 'Erreur lors de l\'ajout de la ligne' }

  // Recalculate totals
  await recalculateDevisTotals(devisId)

  revalidatePath('/dashboard/devis')
  return { success: true }
}

export async function removeDevisLigneAction(ligneId: string, devisId: string): Promise<ActionResult> {
  const supabase = await createServiceRoleClient()

  const { error } = await supabase
    .from('devis_lignes')
    .delete()
    .eq('id', ligneId)

  if (error) return { success: false, error: 'Erreur' }

  await recalculateDevisTotals(devisId)
  revalidatePath('/dashboard/devis')
  return { success: true }
}

async function recalculateDevisTotals(devisId: string) {
  const supabase = await createServiceRoleClient()

  const { data: devis } = await supabase
    .from('devis')
    .select('remise_pourcent, taux_tva')
    .eq('id', devisId)
    .single()

  const { data: lignes } = await supabase
    .from('devis_lignes')
    .select('montant_ht')
    .eq('devis_id', devisId)

  const subtotal = (lignes || []).reduce((sum, l) => sum + Number(l.montant_ht), 0)
  const remise = subtotal * ((devis?.remise_pourcent || 0) / 100)
  const montant_ht = subtotal - remise
  const montant_tva = montant_ht * ((devis?.taux_tva || 20) / 100)
  const montant_ttc = montant_ht + montant_tva

  await supabase
    .from('devis')
    .update({
      montant_ht: Math.round(montant_ht * 100) / 100,
      montant_tva: Math.round(montant_tva * 100) / 100,
      montant_ttc: Math.round(montant_ttc * 100) / 100,
      remise_montant: Math.round(remise * 100) / 100,
    })
    .eq('id', devisId)
}

export async function updateDevisStatusAction(id: string, status: string): Promise<ActionResult> {
  const session = await getSession()
  const supabase = await createServiceRoleClient()

  const updateData: Record<string, unknown> = { status }
  if (status === 'envoye') updateData.sent_at = new Date().toISOString()
  if (status === 'accepte') updateData.date_acceptation = new Date().toISOString().split('T')[0]

  const { error } = await supabase
    .from('devis')
    .update(updateData)
    .eq('id', id)
    .eq('organization_id', session.organization.id)

  if (error) return { success: false, error: 'Erreur' }

  // Email brandé avec devis PDF joint quand le devis est marqué envoyé
  if (status === 'envoye') {
    try {
      const { data: devis } = await supabase
        .from('devis')
        .select('*, client:clients(*), contact:contacts(prenom, nom, email), formation:formations(intitule, reference), lignes:devis_lignes(*)')
        .eq('id', id).single()
      const cli: any = (devis as any)?.client
      const ct: any = (devis as any)?.contact
      const toEmail = ct?.email || cli?.email
      if (devis && toEmail) {
        const { data: org } = await supabase.from('organizations').select('*').eq('id', session.organization.id).single()
  const { withDocumentLogo } = await import('@/lib/pdf/org-logo')
  const orgDoc = await withDocumentLogo(supabase, org)
        const { renderToBuffer } = await import('@react-pdf/renderer')
        const { createElement } = await import('react')
        const { DevisPDF } = await import('@/lib/pdf/devis-pdf')
        const buffer = await renderToBuffer(createElement(DevisPDF, { devis: devis as any, org: orgDoc }) as any)
        const fmtEuro = (n: number) => new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(n || 0)
        const fmtDate = (s: string | null) => s ? new Date(s).toLocaleDateString('fr-FR') : '—'
        const recipientName = ct?.prenom || ct?.nom
          ? `${ct.prenom || ''} ${ct.nom || ''}`.trim()
          : cli?.raison_sociale || 'Madame, Monsieur'

        const { sendDocumentEmail } = await import('@/lib/email')
        await sendDocumentEmail({
          to: toEmail,
          orgName: org?.name || 'Lab Learning',
          orgEmail: (org as any)?.email_contact || org?.email,
          orgLogoUrl: (org as any)?.logo_url,
          qualiopiCertified: (org as any)?.is_qualiopi !== false,
          recipientName,
          subject: `Votre devis ${(devis as any).numero} — ${fmtEuro(Number((devis as any).montant_ttc || 0))} TTC`,
          docTitle: `Votre devis ${(devis as any).numero}`,
          intro: `Veuillez trouver ci-joint votre devis pour la prestation de formation${(devis as any).formation?.intitule ? ` "${(devis as any).formation.intitule}"` : ''}.`,
          metadata: [
            ['Montant HT', fmtEuro(Number((devis as any).montant_ht || 0))],
            ['Montant TTC', fmtEuro(Number((devis as any).montant_ttc || 0))],
            ['Valide jusqu\'au', fmtDate((devis as any).date_validite)],
            ['Référence', (devis as any).numero || ''],
          ],
          pdfBuffer: Buffer.from(buffer),
          pdfFilename: `devis-${(devis as any).numero}.pdf`,
          footerNote: 'Pour accepter ce devis, retournez-le signé avec la mention « Bon pour accord ».',
        })
      }
    } catch (e) { console.error('[email devis]', e) }
  }

  await logAudit({ action: 'update_status', entity_type: 'devis', entity_id: id, details: { status } })
  revalidatePath('/dashboard/devis')
  return { success: true }
}

export async function convertDevisToConventionAction(devisId: string): Promise<ActionResult> {
  const session = await getSession()
  const supabase = await createServiceRoleClient()

  const { data: devis } = await supabase
    .from('devis')
    .select('*, client:clients(raison_sociale, type), formation:formations(intitule, duree_heures)')
    .eq('id', devisId)
    .single()

  if (!devis) return { success: false, error: 'Devis introuvable' }
  if (!devis.formation_id) return { success: false, error: 'Aucune formation liée au devis' }

  // Generate convention number
  const { count } = await supabase
    .from('conventions')
    .select('*', { count: 'exact', head: true })
    .eq('organization_id', session.organization.id)

  const numero = `CONV-${new Date().getFullYear()}-${String((count || 0) + 1).padStart(3, '0')}`

  const { data: convention, error } = await supabase
    .from('conventions')
    .insert({
      organization_id: session.organization.id,
      numero,
      type: 'inter_entreprise',
      client_id: devis.client_id,
      contact_id: devis.contact_id,
      formation_id: devis.formation_id,
      devis_id: devisId,
      dossier_id: devis.dossier_id,
      objet: devis.objet,
      montant_ht: devis.montant_ht,
      taux_tva: devis.taux_tva,
      montant_ttc: devis.montant_ttc,
      duree_heures: devis.formation?.duree_heures,
      created_by: session.user.id,
    })
    .select()
    .single()

  if (error) return { success: false, error: 'Erreur lors de la création de la convention' }

  // Mark devis as accepted if not already
  if (devis.status !== 'accepte') {
    await supabase.from('devis').update({ status: 'accepte', date_acceptation: new Date().toISOString().split('T')[0] }).eq('id', devisId)
  }

  await logAudit({ action: 'convert_to_convention', entity_type: 'devis', entity_id: devisId, details: { convention_id: convention.id } })
  revalidatePath('/dashboard/devis')
  revalidatePath('/dashboard/conventions')
  return { success: true, data: { convention_id: convention.id } }
}

export async function deleteDevisAction(id: string): Promise<ActionResult> {
  const session = await getSession()
  const supabase = await createServiceRoleClient()

  const { error } = await supabase
    .from('devis')
    .delete()
    .eq('id', id)
    .eq('organization_id', session.organization.id)

  if (error) return { success: false, error: 'Erreur lors de la suppression' }

  await logAudit({ action: 'delete', entity_type: 'devis', entity_id: id })
  revalidatePath('/dashboard/devis')
  return { success: true }
}
